### ISSUE TITLE
Dedicated servers

### ISSUE THREAD

**Issue by ghermans** [idevelopment/Hcrm#121]
# Manage dedicated servers

## TODO: 

- [ ] Add: DedicatedServersController
- [ ] Add: Migrations
- [ ] Add: Model and relationship
- [ ] Add:   `resources/views/dedicatedservers/index`
- [ ] Add:   `resources/views/dedicatedservers/update`
- [ ] Add:   `resources/views/dedicatedservers/register`

### Model relationships
- servers to customer (many to many)
- servers to serverips (One To Many)

#### servers
- customer_id
- serverName
- reference
- provider
- provider_id
- location
- network
- startDate
- endDate
- serviceLevelAgreement

#### serverips
- type
- ip
- reverseLookup

#### serversoftware
- name
- startDate
- endDate

**Comment by Tjoosten** [comment]
Migrations added
