### ISSUE TITLE
Role & permission management

### ISSUE THREAD

**Issue by ghermans** [idevelopment/Hcrm#54]
Users can add new roles and assign permissions to the new role.

## Todo 

- [x] Create a view to list all roles
- [ ] Create a view to create a new role and select the permissions that are assigned to this role.
- [ ] Create a view to edit a role and assign permissions

## Default roles
- Admin
- Administration
- Technical

## Default permissions
**Customers**
- [x] create_customer
- [x] list_customers
- [x] edit_customer
- [x] remove customer

**Departments**
- [x] create_department
- [x] list_departments
- [x] edit_department
- [x] remove department

**Support tickets**
- [x] create_ticket
- [x] list_tickets
- [x] edit_ticket
- [x] remove ticket

**Employees**
- [x] create_user
- [x] list_users
- [x] edit_user
- [x] remove user

**Comment by ghermans** [comment]
## Todo 

- [ ] Create a view to list all roles
- [ ] Create a view to create a new role and select the permissions that are assigned to this role.

**Comment by ghermans** [comment]
@Tjoosten the todo tasks are still open so i reopened this issue.

**Comment by ghermans** [comment]
@Tjoosten can you take this one?

**Comment by Tjoosten** [comment]
I separate that one from this issue.
