### ISSUE TITLE
Fix scss linting errors 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/Hcrm#82]
Improve the *`SCSS`* so we can improve the code quality and on a later base we can set easier standards. 

### TODO: 

- [x] Add: scss-lint config file in the repo. 
- [x] Add: Testing support for `TravisCI`.
- [x] Fix:   `resources/assets/sass/_modules/_variables.scss`
- [x] Fix: `resources/assets/sass/_partials/_buttons.scss`
- [x] Fix: `resources/assets/sass/_partials/_dropdown.scss`
- [x] Fix: `resources/assets/sass/_partials/_forms.scss`
- [x] Fix: `resources/assets/sass/_partials/_general.scss`
- [x] Fix: `resources/assets/sass/_partials/_lists.scss`
- [x] Fix: `resources/assets/sass/_partials/_navbar.scss`
- [x] Fix: `resources/assets/sass/_partials/_notifications.scss`
- [x] Fix: `resources/assets/sass/_partials/_panels.scss`
- [ ] Fix: `resources/assets/sass/_partials/_typography.scss`

### Commands: 

```
(Help)    scss-lint -h
(Stats)   scss-lint --exclude assets/sass/_partials/_x-editable.scss --format Stats
(Linting) scss-lint --exclude assets/sass/_partials/_x-editable.scss
```

### Stats: 

```
 62  EmptyLineBetweenBlocks         (across  4 files)
 58  SpaceAfterPropertyColon        (across  6 files)
 56  Indentation                    (across  7 files)
 50  PropertySortOrder              (across  8 files)
 43  ColorVariable                  (across  7 files)
 25  NameFormat                     (across  5 files)
 23  SingleLinePerSelector          (across  5 files)
 19  TrailingSemicolon              (across  4 files)
 19  SelectorDepth                  (across  3 files)
 18  SelectorFormat                 (across  5 files)
 18  ImportantRule                  (across  5 files)
 16  MergeableSelector              (across  4 files)
 14  QualifyingElement              (across  3 files)
 10  HexLength                      (across  1 files)
 10  SpaceBeforeBrace               (across  4 files)
  9  VendorPrefix                   (across  3 files)
  8  LeadingZero                    (across  2 files)
  5  SingleLinePerProperty          (across  2 files)
  5  PseudoElement                  (across  2 files)
  4  IdSelector                     (across  2 files)
  3  Comment                        (across  2 files)
  2  DuplicateProperty              (across  1 files)
  2  TrailingWhitespace             (across  2 files)
  2  ZeroUnit                       (across  2 files)
  2  ColorKeyword                   (across  2 files)
  1  BangFormat                     (across  1 files)
  1  HexNotation                    (across  1 files)
---  -----------------------        -----------------
485  total                          (across 11 files)

```
